services:
  downloader:
    container_name: youtube-downloader
    build: .

    volumes:
      - ../jellyfin/media/music:/music

    restart: unless-stopped

    networks:
      - homelab

networks:
  homelab:
    external: true